language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
  
install:
  - pip install -q Django==$DJANGO
  - python setup.py -q install

notifications:
  email: false
#before_script:
#  - "pep8 --exclude=migrations --ignore=E501,E225 src"
#  - pyflakes -x W src
#script:
#  - python setup.py test
