language: python
python:
  - "2.7"
  - "2.7.6"
env:
  - DJANGO_VERSION=1.8.0
  - DJANGO_VERSION=1.8.2
  
install:
  - pip install django==$DJANGO_VERSION
  - pip install Pillow
  
script: python manage.py runserver

notifications:
  email: false
#before_script:
#  - "pep8 --exclude=migrations --ignore=E501,E225 src"
#  - pyflakes -x W src
#script:
#  - python setup.py test
